#!/bin/bash
check="./*"
DIR="/bin/*"
buff="^#!/(.*/)*.*"

for file in $check
do
if [[ -f "$file" && -r "$file" && -x "$file" ]]
then
grep -Eos $buff $file | sed -E "s|^|$file:|"
fi
done  | sort -t ":" -k 2 | awk -F":" '{b[$2]=$1 a[$2]++} END {for(i in a) {print b[i], i, a[i]}}'  | sort -n -r -k 3 
