#!/bin/bash

restFile=$PWD/$1
if [[ $# -ne 1 ]] 
then
	exit 1
fi

for i in $(grep -h $1 ~/.trash.log)
do
	firstTrashArg=$(echo $i | awk -F ":" '{print $1}')
	secondTrashArg=$(echo $i | awk -F ":" '{print $2}')
	if [[ $restFile == $firstTrashArg ]]
	then
		recoverableFile=~/.trash/$secondTrashArg
		if [[ -e $recoverableFile ]]
		then
			echo "Do you want to recover this file - $(basename $firstTrashArg)?"
			echo "Date of remove: $(date --date=@$secondTrashArg)" 
			echo "Do you want continue? [y/n]"
			read answer
			if [[ $answer == "y" || $answer == "д" ]]
			then
    	    	if [[ -d $(dirname $firstTrashArg) ]]
        		then
            	    if [[ -e $firstTrashArg ]]
                	then
						echo "Error recovering! Dublicate files! Remove your version of file!" >&2
            			echo "Do you want replace your file? [y/n]"
						read answer2
						if [[ $answer2 == "y" || $answer2 == "д" ]]
						then
							rm $firstTrashArg
	                       	ln $recoverableFile $firstTrashArg && echo "Successfully"	    				
    	    			else
    	    				echo "Try again later"
    	    				exit 1
						fi
                	else
                        ln $recoverableFile $firstTrashArg
	                fi
   	    		else
            	    echo "$(dirname $firstTrashArg) has been removed! =("
                	ln $recoverableFile ~/$1 && echo "Successfully"
	        	fi
    	    	rm $recoverableFile
        		grep -v $secondTrashArg ~/.trash.log  > ~/.trash0.log
        		mv ~/.trash0.log ~/.trash.log
			fi
		fi
	fi
done